# -*- coding: utf-8 -*-
"""GAI2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUxa1LVvgUVEJU2mxF6-g79smpVUe6Hb
"""

pip install requests pillow

import requests
import io
from PIL import Image
import ipywidgets as widgets
from IPython.display import display, clear_output

# Your Hugging Face token
API_TOKEN = "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"
API_URL = "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0"

headers = {
    "Authorization": f"Bearer {API_TOKEN}"
}

# Input widget
prompt_input = widgets.Text(
    value='',
    placeholder='Describe your image...',
    description='Prompt:',
    layout=widgets.Layout(width='80%')
)

# Button widget
generate_button = widgets.Button(
    description="Generate Image",
    button_style='success'
)

# Output area
output = widgets.Output()

# Button click handler
def generate_image(b):
    output.clear_output()
    with output:
        prompt = prompt_input.value
        print("Generating image...")

        response = requests.post(
            API_URL,
            headers=headers,
            json={"inputs": prompt}
        )

        if response.status_code == 200:
            image = Image.open(io.BytesIO(response.content))
            image.save("generated_image.png")
            print("Image saved as 'generated_image.png'")
            display(image)
        else:
            print(f"Error {response.status_code}:")
            print(response.text)

generate_button.on_click(generate_image)

# Display the UI
display(prompt_input, generate_button, output)