# -*- coding: utf-8 -*-
"""GAI4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_MzCtT4ebbYWBHzmR0HPAImUwbe8NwcH
"""

pip install transformers

pip install torch torchvision torchaudio

pip install pillow

from transformers import BlipProcessor, BlipForConditionalGeneration
from PIL import Image
import requests
import torch

image = Image.open("s1.jpeg").convert('RGB')

processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

inputs = processor(images=image, return_tensors="pt")
out = model.generate(**inputs, max_length=50)
caption = processor.decode(out[0], skip_special_tokens=True)

print("Generated Caption:", caption)

import matplotlib.pyplot as plt

plt.imshow(image)
plt.title(caption)
plt.axis('off')
plt.show()

"""This need to be done for uploading a image to the directory

"""

import os
print(os.getcwd())

from google.colab import files
uploaded = files.upload()